//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Statistic.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meters()
        {
            this.ReadMeters = new HashSet<ReadMeters>();
        }
    
        public int Id_Meters { get; set; }
        public string Title { get; set; }
        public Nullable<int> Type_id { get; set; }
        public int OBJ_id { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual OBJ OBJ { get; set; }
        public virtual TypeMeters TypeMeters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadMeters> ReadMeters { get; set; }
    }
}
