//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Statistic.ADOApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StatisticDataBaseEntities : DbContext
    {
        public StatisticDataBaseEntities()
            : base("name=StatisticDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Meters> Meters { get; set; }
        public virtual DbSet<OBJ> OBJ { get; set; }
        public virtual DbSet<Periods> Periods { get; set; }
        public virtual DbSet<PeriodsRead> PeriodsRead { get; set; }
        public virtual DbSet<Recommendations> Recommendations { get; set; }
        public virtual DbSet<TypeMeters> TypeMeters { get; set; }
        public virtual DbSet<TypeRecome> TypeRecome { get; set; }
        public virtual DbSet<TypeSpecialRecom> TypeSpecialRecom { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ReadMeters> ReadMeters { get; set; }
    }
}
