//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Statistic.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadMeters
    {
        public int Id_RM { get; set; }
        public string Count { get; set; }
        public int PR_id { get; set; }
        public int Meters_id { get; set; }
    
        public virtual Meters Meters { get; set; }
        public virtual PeriodsRead PeriodsRead { get; set; }
    }
}
