//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Statistic.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendations
    {
        public int Id_recomendations { get; set; }
        public int PR_id { get; set; }
        public Nullable<int> typeRecom_id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> TypeSpecialRecom_id { get; set; }
    
        public virtual PeriodsRead PeriodsRead { get; set; }
        public virtual TypeRecome TypeRecome { get; set; }
        public virtual TypeSpecialRecom TypeSpecialRecom { get; set; }
    }
}
